### PR TITLE
IEA

### PR DESCRIPTION
**Pull request by Kajwan**
Added IEA classification.

### CODE REVIEW

**Comment by konstantinstadler** [comment]
Fantastic. Thanks a lot. Any tests you could add?

**Comment by Kajwan** [comment]
What kind of tests are you thinking?

**Comment by konstantinstadler** [comment]
In test_functionality.py you find some example (e.g. test_fao_number_codes).
The idea here is to make sure that the column header works for all entries in the tsv. Just some examples to ensure full functionality. 

Please remove vscode (put in gitignore).

sorry, i need to better explain the contribution. The branch "release_test" is an internal branch for testing release to pypi (to pypitesting). A change to master would be  highly appreciate, but I can also solve on my side. 

I might wait for the merge one or two days, I want to show Mohammed and Candy how this works (thanks for the example 👏🏽 ) ; unless you need that urgently

**Comment by Kajwan** [comment]
Ah I see. 
I don't really have any testing to do. Only issue might be if IEA increases their country resolution, and a region is therefore mistakenly added to an aggregate region (Other Africa, Other non-OECD Asia, or Other non-OECD Americas) instead of itself. However, I don't see how I can test that without having the IEA data available. 

What do you mean by "Please remove vscode (put in gitignore)". It should already be in .gitignore? 

I am no sure if you would like me to do anything now? Should I make a pull request to the master branch or will you do that yourself at some point? And how should I interpret the build error above? Something I should worry about or is that fine?

**Pull request merged**
