### PR TITLE
Add build-system requirements and isort configuration to pyproject.toml

### PR DESCRIPTION
**Pull request by mwtoews**
This implements [PEP 517](https://peps.python.org/pep-0517/) and [PEP 518](https://peps.python.org/pep-0518/) to describe the build-system requirements in `pyproject.toml`.

Other things in this PR:

- Move `isort` configuration to `pyproject.toml`, so these don't need to be repeated when invoking the command
- When building packages, use `python -m build` instead of directly invoking `setup.py` (see [Why you shouldn't invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html))
- Add twine check to see if source and wheel packages are good before uploading to PyPI
- Remove `MANIFEST` and add it to `.gitignore`

### CODE REVIEW

**Comment by konstantinstadler** [comment]
This sounds interesting. 
Would that change the workflow for building/uploading to pypi, or building the conda-forge?

**Comment by konstantinstadler** [comment]
Also, it requires the build package, so this probably should go into the environment.yml file?

**Comment by mwtoews** [comment]
This simplifies the workflow for build/upload for PyPI since you don't need to install the build-time dependencies (often `setuptools` and `wheel`), as this is done in this PR by [build](https://github.com/pypa/build). Both sdist and wheels are built and uploaded to PyPI. And no, `build` should not be added to `environment.yml`, since it is not a run-time dependency.

I don't believe anything else needs to be done with https://github.com/conda-forge/country_converter-feedstock/blob/main/recipe/meta.yaml

**Comment by konstantinstadler** [comment]
Mmmh, but where does build gets installed in your pull request?

Do the changes in pyproject some magic?
Generally, we have the environment.yml as a development environment (it also contains isort, pytest and such things).

**Comment by mwtoews** [comment]
`build` is installed in this PR here: https://github.com/konstantinstadler/country_converter/blob/2b04af13b091b7aaecc56043b98838ab2a3d6a8a/.github/workflows/publish_pypi.yml#L32
(along with [`twine`](https://twine.readthedocs.io/en/stable/) to check the packages before they are uploaded).

But I still don't think `build` should be added to environment.yml, since it is not a runtime or development dependency (pytest, isort, etc.). Or at least I haven't seen it appear as a dependency with other projects. Typically, it's just `pip install build` followed by `python -m build` in a CI workflow used for building and publishing.

Also, I should note that when someone does `pip install country_converter` with the current versions of `pip`, it shows a warning messsage:
>  DEPRECATION: country_converter is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

This PR will obviously resolve the warning.

**Review by konstantinstadler — APPROVED** [review]

**Pull request merged**
