### PR TITLE
Added classification from Cecilia2050

### PR DESCRIPTION
**Pull request by bixiou**
Cecilia 2050 is a project building hypothetical input-output tables of the future, relying on 4 world regions: EU, other high income countries (HI), ermerging countries (BX) and rest of the world (RoW). Only BX and HI were coded, as EU and RoW can be retrieved from the converter.
The classification was originally defined here: https://cecilia2050.eu/system/files/De%20Koning%20et%20al.%20%282014%29_Scenarios%20for%202050_0.pdf

### CODE REVIEW

**Comment by konstantinstadler** [comment]
Thanks a lot for that! I will check that when I am back from paternity leave (September)

**Comment by konstantinstadler** [comment]
Ok. I merge this now into develop - I will check the bug with WF to NaN before it goes into the master branch.
Thanks a lot again for your work!

**Comment by konstantinstadler** [comment]
Think you forgot to add RoW and EU to the Cicila classification. I did that now, available already in the develop branch (commit b97b977). I also change Taiwan from BX to HI according to the source.
Will be on master soon, but please test and check

**Comment by bixiou** [comment]
Thank's! It's because in the code I used to aggregate regions, I didn't need to precise RoW and EU, but you're right I should've done it. (And my bad for Taiwan).

**Comment by konstantinstadler** [comment]
No problem - just add an issue if you encounter some further bugs

**Pull request merged**
